import {
  Zap,
  Bot,
  Wrench,
  Globe,
  GitBranch,
  ShieldCheck,
  Code,
  Repeat,
  Workflow,
  CircleStop,
  PenLine,
  Filter,
  Scissors,
  Merge,
  Minus,
  ArrowUpDown,
  Combine,
  Split,
  CopyX,
  Tags,
  Hash,
  CalendarClock,
  Sigma,
  MessageSquare,
} from "lucide-react";
import type { ElementType } from "react";
import type { NodeType } from "@/types/domain";

export interface NodeTypeConfig {
  type: NodeType;
  label: string;
  description: string;
  icon: ElementType;
  category: "triggers" | "agents" | "logic" | "actions";
  accentVar: string;
  bgVar: string;
}

export const NODE_TYPE_CONFIGS: Record<NodeType, NodeTypeConfig> = {
  trigger: {
    type: "trigger",
    label: "Trigger",
    description: "Start the workflow",
    icon: Zap,
    category: "triggers",
    accentVar: "--success",
    bgVar: "--success-surface",
  },
  agent: {
    type: "agent",
    label: "Agent",
    description: "Run an AI agent",
    icon: Bot,
    category: "agents",
    accentVar: "--primary",
    bgVar: "--accent",
  },
  tool: {
    type: "tool",
    label: "Tool",
    description: "Execute an external tool",
    icon: Wrench,
    category: "actions",
    accentVar: "--warning",
    bgVar: "--warning-surface",
  },
  api: {
    type: "api",
    label: "HTTP Request",
    description: "Call an external API",
    icon: Globe,
    category: "actions",
    accentVar: "--chart-6",
    bgVar: "--surface-2",
  },
  decision: {
    type: "decision",
    label: "Decision",
    description: "Branch on conditions",
    icon: GitBranch,
    category: "logic",
    accentVar: "--chart-4",
    bgVar: "--warning-surface",
  },
  approval: {
    type: "approval",
    label: "Approval",
    description: "Wait for human approval",
    icon: ShieldCheck,
    category: "logic",
    accentVar: "--chart-5",
    bgVar: "--danger-surface",
  },
  code: {
    type: "code",
    label: "Code",
    description: "Run JavaScript code",
    icon: Code,
    category: "actions",
    accentVar: "--neutral",
    bgVar: "--surface-2",
  },
  loop: {
    type: "loop",
    label: "Loop",
    description: "Iterate over a collection",
    icon: Repeat,
    category: "logic",
    accentVar: "--chart-2",
    bgVar: "--info-surface",
  },
  subflow: {
    type: "subflow",
    label: "Sub-workflow",
    description: "Run another workflow",
    icon: Workflow,
    category: "actions",
    accentVar: "--info",
    bgVar: "--info-surface",
  },
  end: {
    type: "end",
    label: "End",
    description: "End the workflow",
    icon: CircleStop,
    category: "logic",
    accentVar: "--danger",
    bgVar: "--danger-surface",
  },
  set: {
    type: "set",
    label: "Edit Fields",
    description: "Set or override item fields",
    icon: PenLine,
    category: "logic",
    accentVar: "--chart-3",
    bgVar: "--surface-2",
  },
  filter: {
    type: "filter",
    label: "Filter",
    description: "Keep items matching a condition",
    icon: Filter,
    category: "logic",
    accentVar: "--chart-4",
    bgVar: "--warning-surface",
  },
  limit: {
    type: "limit",
    label: "Limit",
    description: "Keep the first/last N items",
    icon: Scissors,
    category: "logic",
    accentVar: "--chart-2",
    bgVar: "--info-surface",
  },
  merge: {
    type: "merge",
    label: "Merge",
    description: "Combine items from inputs",
    icon: Merge,
    category: "logic",
    accentVar: "--info",
    bgVar: "--info-surface",
  },
  noop: {
    type: "noop",
    label: "No Op",
    description: "Pass items through unchanged",
    icon: Minus,
    category: "logic",
    accentVar: "--neutral",
    bgVar: "--surface-2",
  },
  sort: {
    type: "sort",
    label: "Sort",
    description: "Order items by a field",
    icon: ArrowUpDown,
    category: "logic",
    accentVar: "--chart-2",
    bgVar: "--info-surface",
  },
  aggregate: {
    type: "aggregate",
    label: "Aggregate",
    description: "Combine items into one",
    icon: Combine,
    category: "logic",
    accentVar: "--chart-3",
    bgVar: "--surface-2",
  },
  splitOut: {
    type: "splitOut",
    label: "Split Out",
    description: "Array field → one item each",
    icon: Split,
    category: "logic",
    accentVar: "--chart-4",
    bgVar: "--warning-surface",
  },
  removeDuplicates: {
    type: "removeDuplicates",
    label: "Remove Duplicates",
    description: "Drop repeated items",
    icon: CopyX,
    category: "logic",
    accentVar: "--chart-5",
    bgVar: "--surface-2",
  },
  renameKeys: {
    type: "renameKeys",
    label: "Rename Keys",
    description: "Rename item fields",
    icon: Tags,
    category: "logic",
    accentVar: "--chart-6",
    bgVar: "--surface-2",
  },
  crypto: {
    type: "crypto",
    label: "Crypto",
    description: "Hash / HMAC a value",
    icon: Hash,
    category: "logic",
    accentVar: "--warning",
    bgVar: "--warning-surface",
  },
  dateTime: {
    type: "dateTime",
    label: "Date & Time",
    description: "Format or shift a date",
    icon: CalendarClock,
    category: "logic",
    accentVar: "--chart-2",
    bgVar: "--info-surface",
  },
  summarize: {
    type: "summarize",
    label: "Summarize",
    description: "Group & count/sum items",
    icon: Sigma,
    category: "logic",
    accentVar: "--chart-3",
    bgVar: "--surface-2",
  },
  slack: {
    type: "slack",
    label: "Slack",
    description: "Post a message to Slack",
    icon: MessageSquare,
    category: "actions",
    accentVar: "--chart-5",
    bgVar: "--accent",
  },
};

export const PALETTE_CATEGORIES = [
  { key: "triggers" as const, label: "Triggers" },
  { key: "agents" as const, label: "Agents" },
  { key: "logic" as const, label: "Logic" },
  { key: "actions" as const, label: "Actions" },
] as const;
